### ISSUE TITLE
Using multiple CircleCI API Tokens

### ISSUE THREAD

**Issue by Skovy** [mtchavez/circleci#24]
I am working on an application that I need to change the API token regularly. Right now it seems the only way to configure this gem is application-wide. Is there an easier way to change the token or can I open a PR?

**Comment by mtchavez** [comment]
Can you expound on your intentions for multiple API tokens and what context you are using the gem in?

**Comment by mtchavez** [comment]
Closing due to months of inactivity. Please feel free to re-open with further details if needed.

**Comment by Skovy** [comment]
@mtchavez my initial comment was made because I was working on a service that would allow multiple people to create an account and integrate with CircleCi so I would need to dynamically set the API token based on the current user.
