### ISSUE TITLE
GET requests failing with 403 Forbidden

### ISSUE THREAD

**Issue by kstevens715** [mtchavez/circleci#324]
I'm currently using an old fork of this gem and API requests to get info on a build started failing today. I believe something changed on CircleCI's side. I fixed the problem in my fork (which I hope to stop using the fork soon). I'm adding the issue here in case it's affecting this main repo as well, since it was kind of a pain to debug.

There's a chance I'll verify this is broken in this main repo and submit a pull request if it is, but since my fork is working it's not much of a priority for me.

## Issue

Getting a build via the following method started failing today:

https://github.com/mtchavez/circleci/blob/a7a2a984df5a1f2c43fe8efbebc2d4e68c1005eb/lib/circleci/build.rb#L31-L33

It was failing with a `403 Forbidden`.

## Steps to reproduce

Call `Build#get`.

## Expected behavior

GET requests should have a successful response code and return the expected body.

## Proposals
On my fork, I was able to fix the issue by making sure not to set the request body for GET requests. Previously, it was getting set to `{}`.

Here's the method I changed to fix the problem:
https://github.com/mtchavez/circleci/blob/a7a2a984df5a1f2c43fe8efbebc2d4e68c1005eb/lib/circleci/request.rb#L50-L54

**Comment by zackse** [comment]
PR #323 has a fix for this as well.

**Comment by kstevens715** [comment]
Closing since a PR already exists to fix this.

**Comment by devinburnette** [comment]
having this problem as well. hope the fix is merged soon!

**Comment by mtchavez** [comment]
#323 merged in and version [2.1.0][gem] of the gem is released with the fix

[gem]: https://rubygems.org/gems/circleci
