### ISSUE TITLE
Ability to specify rest-client certificate verification options

### ISSUE THREAD

**Issue by jantman** [mtchavez/circleci#47]
We're using self-hosted CircleCI Enterprise on our private network, and have it running with a self-signed SSL cert (since it's internal only). Thanks to #10 I can configure the host endpoint (``config.host``), but then all requests fail with a ``RestClient::SSLCertificateNotVerified`` error.

I was able to patch this in inside a script, by converting CircleCi::Http to use [RestClient::Request.execute](http://www.rubydoc.info/github/rest-client/rest-client/RestClient/Request) in place of the ``get`` and ``post`` methods (which are just [thin wrappers](https://github.com/rest-client/rest-client/blob/master/lib/restclient.rb#L65) around execute).

```ruby
module CircleCi
  class Http
    def create_request_args(http_verb, url, body)
      if http_verb == "post"
        return {
          :method => :post,
          :url => url,
          :payload => body,
          :headers => headers
        }
      end
      {   
          :method => :post,
          :url => url,
          :headers => headers
      }
    end

    def request(http_verb, path, body = {})
      url  = "#{@config.host}#{path}"
      args = create_request_args http_verb, url, body

      # this should come from a configuration option                                                                                                                                                           
      args[:verify_ssl] = false

      RestClient::Request.execute(args) do |res, req, raw_res|
        body = res.body.to_s
        body.force_encoding(Encoding::UTF_8)
        code = raw_res.code.to_i

        self.response = body
        self.errors   = []

        handle_response(body, code, path)
        Response.new(self, code, path)
      end
    end
  end
end
```

**Comment by mtchavez** [comment]
New release cut that should address this `v0.2.3`. There is an example in the `README` but an example of setting request configuration is:

```ruby
CircleCi.configure do |config|
  config.token = ENV['CIRCLECI_TOKEN']
  config.request_overrides = {
    verify_ssl: false
  }
end
```
