### ISSUE TITLE
Getting last n builds

### ISSUE THREAD

**Issue by stuffandthings** [mtchavez/circleci#59]
There's an option to get recent builds, but I'd like to be able to get a lot more. Is there a way to change the conditions for what gets added to recent builds? i.e. can I get the last 100, 1000, ... , n builds?

**Comment by mtchavez** [comment]
Thanks for pointing this out. I broke this up into two separate issues #60 and #61. I think the latter of the two is what addresses this. Let me know if I missed something. Closing.

**Comment by stuffandthings** [comment]
Yeah, sounds good! To get around CircleCI's limitation I wrote a rake task to loop over the number of builds I want. Since build numbers are in sequential order, I just iterate from (build_num - n) to build_num and explicitly download the individual builds.

**Comment by mtchavez** [comment]
New build released that should address this `v0.2.3`. See the `README` for the usage but essentially you can pass a hash to the `CircleCi::Project.recent_builds` method to use limit, offset, and filter. In addition there is `CircleCi::RecentBuilds.get` that allows you to get all recent builds for your user which also takes params where limit and offset can be used.
