### ISSUE TITLE
to list project vars  - it's envvars (plural) and not envvar

### ISSUE THREAD

**Issue by jedi4ever** [mtchavez/circleci#70]
Readme contains a description to list the vars of a project
<https://github.com/mtchavez/circleci#envvar>

```
res = CircleCi::Project.envvar 'user', 'repo'
res.success?
```

I needed to replace `envvar` with `envvars`.
Happy to send a PR but I it by design that list is envvars (plural)
and the command set/get are with envvar as endpoint.

**Comment by mtchavez** [comment]
Yup, good catch. Thanks for updating.
