### ISSUE TITLE
Update README on usage

### ISSUE THREAD

**Issue by mtchavez** [mtchavez/circleci#87]
## Issue

Version `1.1.0` introduced new object/class approach to interacting with the API. This also allows for optionally overriding the config per request or class instance.

## Expected behavior

- [ ] Update the `README` on usage of gem with new approach
- [ ] Mention the deprecation of class methods
- [ ] Document eventual removal of class methods in future version

**Comment by jbcom** [comment]
In terms of prioritization would it be possible to get some simple examples of how for example recent_builds would work in the new setup? How parameters are passed is to me now a little confusing. Going through the code and trying to get it all to work with instance methods and I've gotten pretty far but can't seem to go any further without more of an understanding of how the new model handles filters and restraints. You're a saint for making this thing! Looking forward to seeing the docs. 👍

**Comment by mtchavez** [comment]
Crudely updated the `README` on using the new classes and interacting with the API endpoints. Will eventually want to get them in the Yardoc. Let me know if anything is not working or making sense.
