### ISSUE TITLE
Regression: build_parameters no longer being sent

### ISSUE THREAD

**Issue by suan** [mtchavez/circleci#91]
## Issue
CircleCI Build Parameters are no longer being sent - looks like all that code was accidentally removed?

## Steps to reproduce
Neither doing `CircleCi::Project.build_branch(org, repo, branch, envvar1: 'val')` OR `project.build_branch(branch, envvar1: 'val')` actually sends over build parameters anymore

## Expected behavior
One or both of those should correctly send over build parameters, like they used to

**Comment by mtchavez** [comment]
@suan Have you tried the example in the `README`?

```ruby
# Passing build parameters in the post body
build_params = { build_parameters: { 'MY_TOKEN' => '123asd123asd' } }
res = CircleCi::Project.build_branch 'username', 'reponame', 'branch', {}, build_params
```

**Comment by mtchavez** [comment]
Updated the `CHANGELOG` so there is no further confusion. Closing this out but let me know if you have any issues still.
