### ISSUE TITLE
Several of the GET API endpoints allow URL params

### ISSUE THREAD

**Issue by ghostsquad** [mtchavez/circleci#97]
## Issue

Several of the `GET` API endpoints allow URL params, but that's not consistently supported.

Examples:
https://circleci.com/docs/api/v1-reference/#recent-builds
https://circleci.com/docs/api/v1-reference/#recent-builds-project
https://circleci.com/docs/api/v1-reference/#recent-builds-project-branch

https://github.com/mtchavez/circleci/blob/master/lib/circleci/project.rb#L146
vs
https://github.com/mtchavez/circleci/blob/master/lib/circleci/project.rb#L136

## Steps to reproduce

N/A

## Expected behavior

All endpoints support params (whether the API uses them or not may not be important)

## Proposals

This is probably an easy fix to update methods to allow params.

**Comment by mtchavez** [comment]
Fixed in #100
